// ⚠️ Ne pas modifier ce fichier — Do not edit this file
import type { Plugin } from 'vite'
import fs from 'fs'
import path from 'path'

/**
 * Vite plugin that auto-detects assets in public/ at build time.
 *
 * For non-developers: just drop your files in the right folders:
 * - Photo/image: public/images/ (any .jpg, .jpeg, .png, or .webp)
 * - CV PDF (French): public/cv/fr/ (any .pdf)
 * - CV PDF (English): public/cv/en/ (any .pdf)
 *
 * The plugin will find them automatically — no config needed.
 * If you set `personal.photo` or `pdf.path` in resume-config.ts, those take priority.
 */

export interface DetectedAssets {
  photo: string | null
  pdf: Record<string, string>
}

const IMAGE_EXTENSIONS = ['.jpg', '.jpeg', '.png', '.webp']

function findFirstFile(dir: string, extensions: string[]): string | null {
  if (!fs.existsSync(dir)) return null
  const files = fs.readdirSync(dir)
  for (const file of files) {
    const ext = path.extname(file).toLowerCase()
    if (extensions.includes(ext)) {
      return file
    }
  }
  return null
}

export function assetsDetectPlugin(): Plugin {
  const virtualModuleId = 'virtual:detected-assets'
  const resolvedVirtualModuleId = '\0' + virtualModuleId
  const detectedAssets: DetectedAssets = { photo: null, pdf: {} }

  return {
    name: 'assets-detect',

    buildStart() {
      const publicDir = path.resolve(process.cwd(), 'public')

      // --- Detect photo/image in public/images/ ---
      const imagesDir = path.join(publicDir, 'images')
      const photoFile = findFirstFile(imagesDir, IMAGE_EXTENSIONS)
      if (photoFile) {
        detectedAssets.photo = `/images/${photoFile}`
      }

      // --- Detect PDFs in public/cv/<lang>/ ---
      const cvDir = path.join(publicDir, 'cv')
      if (fs.existsSync(cvDir)) {
        const langDirs = fs.readdirSync(cvDir).filter((entry) => {
          const fullPath = path.join(cvDir, entry)
          return fs.statSync(fullPath).isDirectory()
        })

        for (const lang of langDirs) {
          const langDir = path.join(cvDir, lang)
          const pdfFile = findFirstFile(langDir, ['.pdf'])
          if (pdfFile) {
            detectedAssets.pdf[lang] = `/cv/${lang}/${pdfFile}`
          }
        }
      }

      // Log what was found
      if (detectedAssets.photo) {
        console.log(`[assets-detect] 📷 Image found: ${detectedAssets.photo}`)
      }
      const pdfLangs = Object.keys(detectedAssets.pdf)
      if (pdfLangs.length > 0) {
        for (const lang of pdfLangs) {
          console.log(`[assets-detect] 📄 PDF found (${lang}): ${detectedAssets.pdf[lang]}`)
        }
      }
    },

    resolveId(id: string) {
      if (id === virtualModuleId) {
        return resolvedVirtualModuleId
      }
    },

    load(id: string) {
      if (id === resolvedVirtualModuleId) {
        return `export const detectedAssets = ${JSON.stringify(detectedAssets)};`
      }
    },
  }
}
